root: true
env:
  es22022: true
  browser: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project": ./tsconfig.json
ingorePatterns:
  - "vite.config.ts"
  - "dist/"
  - "public/"
  - "helm_chart/"
  - "docker/"
settings:
  react: 
    version: detect
plugins:
  - "@typescript-eslint"
  - "import"
  - "react"
  - "@emotion"
  - "@tanstack/query"
  - "prettier"
  - "jest"
  - "jest-dom"
  - "testing-library"
  - "simple-import-sort"
extends:
  - "eslint:recommend"
  - "plugin:@typescript-eslint/recommend"
  - "plugin:@typescript-eslint/recommend-type-checked"
  - "plugin:import/typescript"
  - "plugin:react/recommend"
  - "plugin:react-hooks/recommend"
  - "plugin:@tanstack/eslint-plugin-query/recommend"
  - "plugin:prettier/recommend"
rules:
  prettier/prettier: off
  no-console: off
  arrow-body-style:
    - error
    - as-needed
  guard-for-in: off
  newline-per-chained-call: off
  no-shadow: off
  import/consistent-type-specifier-style:
    - error
    - prefer-inline
  import/no-duplicates:
    - error
    - prefer-inline: true
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/consistent-type-imports": error
  "@typescript-eslint-switch-exhaustiveness-check": error
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreVoid: true
  import/prefer-default-export: off
  "@typescript-eslint/no-explicit-any": off
  react/react-in-jsx-scope: off
  react/function-component-definition: off
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  import/first: error
  import/newline-after-import: error
  react/self-closing-comp:
    - error
    - component: true
      html: true
  #
  #
  overrides:
    - files:
      - test/**/*.test.ts
      - test/**/*.test.tsx
      extends:
        - plugin:vitest/recommend
        - plugin:jest-dom/recommend
        - plugin:testing-library/dom
        - plugin:testing-library/react
      rules:
        no-console: warn
        no-empty-functions: off
        no-magic-numbers: off
        no-shadow: off
        "@typescript-eslint/no-empty-functions": off
        vitest/no-commented-out-tests: warn
        vitest/expect-expect: error
        testing-library/await-async-queries: error
        testing-library/no-await-sync-queries: error
        testing-library/no-debugging-utils: warn
        testing-library/no-dom-import: off
